'use client';
import {useEffect,useMemo,useState} from 'react';
import {Activity,ArrowUpRight,BriefcaseBusiness,CalendarDays,CheckCircle2,CircleHelp,Clock3,ExternalLink,Filter,Globe2,Layers3,LoaderCircle,Radar,RefreshCw,Search,ShieldAlert,TrendingUp,XCircle} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import type {Job,SourceStatus} from '@/lib/radar';

type Report={fetchedAt:number;active:number;possible:number;review:number;excluded:number;companies:number;topSkills:{name:string;count:number}[];topJobs:{id:string;title:string;company:string;score:number}[];note:string};
type Payload={jobs:Job[];report:Report;sources:SourceStatus[];updatedAt:number;mode:'snapshot'|'live';error?:string};
const fitText={possible:'可优先核实',review:'条件待核实',excluded:'存在明确门槛'};
const fmt=(n:number|null)=>n?new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(n):'未提供';

export default function Home(){
  const [data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[expanded,setExpanded]=useState<string|null>(null);
  async function load(live=false){if(live)setRefreshing(true);else setLoading(true);setError('');try{const r=await fetch(`/api/radar${live?'?live=1':''}`,{cache:'no-store'});const d=await r.json() as Payload;if(!r.ok)throw new Error(d.error||'职位读取失败');setData(d)}catch(e){setError(e instanceof Error?e.message:'职位读取失败')}finally{setLoading(false);setRefreshing(false)}}
  useEffect(()=>{let active=true;fetch('/api/radar',{cache:'no-store'}).then(async r=>{const d=await r.json() as Payload;if(!r.ok)throw new Error(d.error||'职位读取失败');if(active)setData(d)}).catch(e=>{if(active)setError(e instanceof Error?e.message:'职位读取失败')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return (data?.jobs||[]).filter(j=>(filter==='all'||j.fit===filter)&&(!q||`${j.title} ${j.company} ${j.team} ${j.skills.join(' ')}`.toLowerCase().includes(q)))},[data,filter,query]);
  const report=data?.report;
  return <main className="shell"><aside className="rail"><div className="brand"><span><Radar size={22}/></span><div><strong>AI Job Radar</strong><small>招聘情报工作台</small></div></div><div className="rail-label">WORKSPACE</div><div className="rail-item active"><Layers3 size={17}/> 职位雷达 <span>01</span></div><a className="rail-item" href="#report"><CalendarDays size={17}/> 当次日报</a><a className="rail-item" href="#sources"><Globe2 size={17}/> 数据来源</a><div className="rail-note"><div><Activity size={16}/> 数据原则</div><p>只展示公开招聘页返回的岗位。学历和经验缺失时标记待核实，点击原岗位再确认。</p></div></aside>
  <div className="main"><header className="top"><div className="crumb">工作台 <span>/</span> 职位雷达</div><div className="top-right"><span className="live-dot"/> 公开职位数据 <span className="top-divider"/> 上海 · China</div></header><div className="body"><div className="heading"><div><div className="eyebrow"><span/> MARKET SIGNAL / SHANGHAI</div><h1>上海职位雷达</h1><p>从公开招聘页提取岗位，优先排查学历与经验门槛，再决定是否投递。</p></div><Button className="refresh" onClick={()=>void load(true)} disabled={refreshing||loading}>{refreshing?<LoaderCircle className="spin" size={16}/>:<RefreshCw size={16}/>} 抓取最新</Button></div>
  <div className="coverage"><Globe2 size={17}/><span>当前覆盖 <b>Yuno、Xsolla、WGSN、dLocal</b> 四家公司的 Lever 公开招聘页；这不是全上海职位库。</span></div>
  {error&&<div className="error" role="alert"><XCircle size={18}/>{error}<Button variant="outline" size="sm" onClick={()=>void load()}>重试</Button></div>}
  {loading&&!data?<div className="loading"><LoaderCircle size={23} className="spin"/> 正在读取职位来源…</div>:data&&<>
    <section className="stats" aria-label="职位概况"><div className="stat"><span>当前上海岗位</span><strong>{report?.active||0}<small>个</small></strong><p><BriefcaseBusiness size={14}/> 四家来源合计</p></div><div className="stat"><span>可优先核实</span><strong className="green">{report?.possible||0}<small>个</small></strong><p><CheckCircle2 size={14}/> 明确友好表述</p></div><div className="stat"><span>条件待核实</span><strong className="amber">{report?.review||0}<small>个</small></strong><p><CircleHelp size={14}/> 学历或经验未写明</p></div><div className="stat"><span>存在明确门槛</span><strong>{report?.excluded||0}<small>个</small></strong><p><ShieldAlert size={14}/> 需核对原文</p></div></section>
    <div className="columns"><div className="left"><section className="panel jobs-panel"><div className="panel-title"><div><div className="eyebrow">OPPORTUNITIES</div><h2>岗位列表 <span>{filtered.length}</span></h2></div><div className="timestamp"><Clock3 size={14}/> {fmt(data.updatedAt)} 更新 · {data.mode==='live'?'实时读取':'已存快照'}</div></div><div className="toolbar"><div className="search"><Search size={17}/><input aria-label="搜索职位、公司或技能" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索职位、公司或技能"/></div><Filter size={17} className="filter-icon"/></div><Tabs value={filter} onValueChange={setFilter} className="fit-tabs"><TabsList><TabsTrigger value="all">全部</TabsTrigger><TabsTrigger value="possible">优先核实</TabsTrigger><TabsTrigger value="review">待核实</TabsTrigger><TabsTrigger value="excluded">有门槛</TabsTrigger></TabsList></Tabs>
    {filtered.length?<div className="job-list">{filtered.map(job=><article className="job" key={job.id}><div className="job-top"><div className="company-icon">{job.company.slice(0,1).toUpperCase()}</div><div className="job-core"><div className="job-title-row"><h3>{job.title}</h3><span className={`fit ${job.fit}`}>{fitText[job.fit]}</span></div><p>{job.company} <span>·</span> {job.location} <span>·</span> {job.team}</p></div><div className="score"><strong>{job.score}</strong><small>参考分</small></div></div><div className="tags">{job.skills.slice(0,4).map(s=><span key={s}>{s}</span>)}<span>{job.salary}</span></div><div className="job-actions"><button onClick={()=>setExpanded(expanded===job.id?null:job.id)}>{expanded===job.id?'收起依据':'查看依据'} <ArrowUpRight size={14}/></button><a href={job.applyUrl} target="_blank" rel="noopener noreferrer">查看原岗位 <ExternalLink size={14}/></a></div>{expanded===job.id&&<div className="job-detail"><strong>筛选依据</strong><p>{job.reasons.join('；')}</p><strong>原岗位摘要</strong><p>{job.description.slice(0,650)||'原岗位未提供可读取的描述，请打开来源查看。'}{job.description.length>650?'…':''}</p><small>来源：Lever / {job.company} · 首次收录 {fmt(job.firstSeen)}。请到原页面核实岗位仍开放及具体要求。</small></div>}</article>)}</div>:<div className="no-jobs"><Search size={26}/><strong>这个条件下没有岗位</strong><p>试试「全部」或清空关键词。未写清学历和经验的岗位仍可在「待核实」中查看。</p></div>}</section></div>
    <div className="right"><section className="panel report" id="report"><div className="eyebrow">DAILY BRIEF / {new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit'}).format(data.updatedAt)}</div><h2>当次招聘简报</h2><p className="report-lead">本次覆盖 <b>{report?.companies||0}</b> 家公司、<b>{report?.active||0}</b> 个上海岗位。{report?.possible?`其中 ${report.possible} 个写有较友好的门槛表述。`:'暂未发现可直接确认接受高中学历且无需经验的岗位。'}</p><div className="report-divider"/><h3><TrendingUp size={16}/> 高频技能</h3>{report?.topSkills.length?<div className="skill-bars">{report.topSkills.map(s=><div className="skill-row" key={s.name}><span>{s.name}</span><div><i style={{width:`${Math.max(8,100*s.count/Math.max(1,report.topSkills[0].count))}%`}}/></div><b>{s.count}</b></div>)}</div>:<p className="small-muted">本次尚无可统计技能。</p>}<div className="report-divider"/><h3>需要注意</h3><p className="small-muted">{report?.note} 参考分用于排序，不能代替实际申请资格判断。</p></section><section className="panel sources" id="sources"><div className="eyebrow">SOURCE HEALTH</div><h2>数据来源</h2>{data.sources.length?data.sources.map(s=><div className="source" key={s.name}><span className={s.ok?'healthy':'unhealthy'}/><strong>{s.name}</strong><span>{s.ok?`${s.count} 个上海岗位`:'读取失败'}</span></div>):<p className="small-muted">暂无来源状态。点击「抓取最新」查看。</p>}<p className="source-note">仅抓取公开职位元数据，申请链接直达公司招聘页。来源异常时保留已存记录并标明更新时间。</p></section></div></div></>}
  <footer>AI Job Radar · 公开招聘信息聚合演示 <span>规则筛选 · 原站核实 · 不自动投递</span></footer></div></div></main>;
}
